Znika feature sidebar
turchin-aa/Devico_FinalProject_Client pull request #4
Opened 2022-04-29 17:23 UTC by jstkiddin

9k+ - it's with yarn and ect

2022-04-29 17:48 UTC, VolodymyrDevico requested changes

2022-04-29 17:48 UTC, VolodymyrDevico commented on src/components/Navigation/NavBar.tsx
> +// function ifLoddedIn(){
remove commented stuff

2022-04-29 17:48 UTC, VolodymyrDevico commented on src/components/Navigation/SideBarItem.tsx
> +            icon:<Campaign />,
Icon: Campaign 

 <Icon />

2022-04-29 17:48 UTC, VolodymyrDevico commented on src/components/Navigation/SideBarItem.tsx
> +    function toggleButton(index:any){
useCallback
And don't use any

2022-05-04 14:30 UTC, VolodymyrDevico requested changes

2022-05-04 14:30 UTC, VolodymyrDevico commented on src/components/DynamicIcon.tsx
> +    } else if (name === '4k') {
necessary else

2022-05-04 14:30 UTC, VolodymyrDevico commented on src/components/Navigation/NavBar/NotificationButton.tsx
> +  const handleOpenMenu = (e:any) =>{
use callback and remove any type

2022-05-04 14:30 UTC, VolodymyrDevico commented on src/components/Navigation/NavBar/NotificationDropDown.tsx
> +       {/* <ArrowDropUp className={clsx(classes.userBarComponentW, classes.userBarNotifArrow)} fontSize='large'/>       */}
remove

2022-05-04 14:30 UTC, VolodymyrDevico commented on src/components/Navigation/NavBar/dropDownMenu.tsx
> +    return props.logged?setMenu(menuIn):setMenu(menuOut)
if else better to call signature

2022-05-04 14:30 UTC, VolodymyrDevico commented on src/components/Navigation/NavBar/dropDownMenu.tsx
> +            onClick={()=>handleClick(item.name)}
don't use arrow functions at render

2022-05-05 12:03 UTC, ntnshpig requested changes

2022-05-05 12:03 UTC, ntnshpig commented on src/components/Navigation/NavBar/userBarLoggedIn.tsx
> +  // }
don`t leave comments

2022-05-09 07:36 UTC, closed without merging